# Generated by Django 5.2.1 on 2025-06-19 01:53

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen principal del artículo (opcional)', null=True, upload_to=articles.models.article_image_path),
        ),
    ]
