# Generated by Django 5.2.1 on 2025-08-31 18:04

import articles.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date'], 'verbose_name': 'Artículo', 'verbose_name_plural': 'Artículos'},
        ),
        migrations.AddField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Determina si el artículo es visible públicamente', verbose_name='Publicado'),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Descripción para SEO (máximo 160 caracteres)', max_length=160, verbose_name='Meta Descripción'),
        ),
        migrations.AddField(
            model_name='article',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AddField(
            model_name='article',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Visualizaciones'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(help_text='Contenido principal del artículo', verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen principal del artículo (opcional, máximo 5MB)', null=True, upload_to=articles.models.article_image_path, verbose_name='Imagen Principal'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='Título del artículo (máximo 255 caracteres)', max_length=255, verbose_name='Título'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-date'], name='articles_ar_date_fe9a8c_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['author'], name='articles_ar_author__8895b2_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_published'], name='articles_ar_is_publ_c4f5ce_idx'),
        ),
    ]
