version: '3.8'

services:
  # Aplicación Django con SQLite
  web:
    build: .
    container_name: newspaper_web
    entrypoint: ["./entrypoint.sh"]
    volumes:
      - .:/app
      - db_volume:/app/data
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
    restart: unless-stopped

volumes:
  db_volume: